// Bocy Merchant Database — UK merchant patterns
// Ported from web app
const MERCHANT_DB = {
// SUBSCRIPTIONS (isSubscription: true)
'netflix':{name:'Netflix',category:'Subscriptions',isSubscription:true},
'spotify':{name:'Spotify',category:'Subscriptions',isSubscription:true},
'disney+':{name:'Disney+',category:'Subscriptions',isSubscription:true},
'disney plus':{name:'Disney+',category:'Subscriptions',isSubscription:true},
'amazon prime video':{name:'Prime Video',category:'Subscriptions',isSubscription:true},
'prime video':{name:'Prime Video',category:'Subscriptions',isSubscription:true},
'apple tv':{name:'Apple TV+',category:'Subscriptions',isSubscription:true},
'apple music':{name:'Apple Music',category:'Subscriptions',isSubscription:true},
'youtube premium':{name:'YouTube Premium',category:'Subscriptions',isSubscription:true},
'youtube music':{name:'YouTube Music',category:'Subscriptions',isSubscription:true},
'now tv':{name:'NOW TV',category:'Subscriptions',isSubscription:true},
'audible':{name:'Audible',category:'Subscriptions',isSubscription:true},
'openai':{name:'ChatGPT',category:'Subscriptions',isSubscription:true},
'chatgpt':{name:'ChatGPT',category:'Subscriptions',isSubscription:true},
'anthropic':{name:'Claude',category:'Subscriptions',isSubscription:true},
'claude':{name:'Claude',category:'Subscriptions',isSubscription:true},
'midjourney':{name:'Midjourney',category:'Subscriptions',isSubscription:true},
'adobe':{name:'Adobe',category:'Subscriptions',isSubscription:true},
'canva':{name:'Canva',category:'Subscriptions',isSubscription:true},
'figma':{name:'Figma',category:'Subscriptions',isSubscription:true},
'notion':{name:'Notion',category:'Subscriptions',isSubscription:true},
'microsoft 365':{name:'Microsoft 365',category:'Subscriptions',isSubscription:true},
'office 365':{name:'Microsoft 365',category:'Subscriptions',isSubscription:true},
'google one':{name:'Google One',category:'Subscriptions',isSubscription:true},
'dropbox':{name:'Dropbox',category:'Subscriptions',isSubscription:true},
'nordvpn':{name:'NordVPN',category:'Subscriptions',isSubscription:true},
'expressvpn':{name:'ExpressVPN',category:'Subscriptions',isSubscription:true},
'lovable':{name:'Lovable',category:'Subscriptions',isSubscription:true},
'cursor':{name:'Cursor',category:'Subscriptions',isSubscription:true},
'headspace':{name:'Headspace',category:'Subscriptions',isSubscription:true},
'calm':{name:'Calm',category:'Subscriptions',isSubscription:true},
'strava':{name:'Strava',category:'Subscriptions',isSubscription:true},
'peloton':{name:'Peloton',category:'Subscriptions',isSubscription:true},
'pure gym':{name:'PureGym',category:'Subscriptions',isSubscription:true},
'puregym':{name:'PureGym',category:'Subscriptions',isSubscription:true},
'the gym':{name:'The Gym',category:'Subscriptions',isSubscription:true},
'david lloyd':{name:'David Lloyd',category:'Subscriptions',isSubscription:true},
'skillshare':{name:'Skillshare',category:'Subscriptions',isSubscription:true},
'masterclass':{name:'MasterClass',category:'Subscriptions',isSubscription:true},
'duolingo':{name:'Duolingo',category:'Subscriptions',isSubscription:true},
'paramount+':{name:'Paramount+',category:'Subscriptions',isSubscription:true},
'paramount plus':{name:'Paramount+',category:'Subscriptions',isSubscription:true},
'crunchyroll':{name:'Crunchyroll',category:'Subscriptions',isSubscription:true},
'xbox game pass':{name:'Xbox Game Pass',category:'Subscriptions',isSubscription:true},
'ps plus':{name:'PS Plus',category:'Subscriptions',isSubscription:true},
'playstation plus':{name:'PS Plus',category:'Subscriptions',isSubscription:true},
'amazon prime':{name:'Amazon Prime',category:'Subscriptions',isSubscription:true},
'icloud':{name:'iCloud',category:'Subscriptions',isSubscription:true},
'apple.com/bill':{name:'Apple Subscription',category:'Subscriptions',isSubscription:true},
'tidal':{name:'Tidal',category:'Subscriptions',isSubscription:true},
'deezer':{name:'Deezer',category:'Subscriptions',isSubscription:true},

// DEBT PAYMENTS (isSubscription: false)
'american express':{name:'American Express',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'amex':{name:'American Express',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'capital one':{name:'Capital One',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'capitalone':{name:'Capital One',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'barclaycard':{name:'Barclaycard',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'mbna':{name:'MBNA',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'aqua':{name:'Aqua',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'vanquis':{name:'Vanquis',category:'Debt Payments',subcategory:'Credit Card',isSubscription:false},
'klarna':{name:'Klarna',category:'Debt Payments',subcategory:'BNPL',isSubscription:false},
'clearpay':{name:'Clearpay',category:'Debt Payments',subcategory:'BNPL',isSubscription:false},
'afterpay':{name:'Afterpay',category:'Debt Payments',subcategory:'BNPL',isSubscription:false},
'zilch':{name:'Zilch',category:'Debt Payments',subcategory:'BNPL',isSubscription:false},
'laybuy':{name:'Laybuy',category:'Debt Payments',subcategory:'BNPL',isSubscription:false},

// TRANSFERS (isSubscription: false)
'transfer to':{name:'Transfer',category:'Transfers',isSubscription:false},
'transfer from':{name:'Transfer',category:'Transfers',isSubscription:false},
'standing order':{name:'Standing Order',category:'Transfers',isSubscription:false},
'faster payment':{name:'Faster Payment',category:'Transfers',isSubscription:false},
'pot transfer':{name:'Pot Transfer',category:'Transfers',isSubscription:false},

// TRANSPORT (isSubscription: false)
'tfl':{name:'TfL',category:'Transport',isSubscription:false},
'oyster':{name:'Oyster',category:'Transport',isSubscription:false},
'trainline':{name:'Trainline',category:'Transport',isSubscription:false},
'uber':{name:'Uber',category:'Transport',isSubscription:false},
'bolt ':{name:'Bolt',category:'Transport',isSubscription:false,_wordBound:true},
'bolt.eu':{name:'Bolt',category:'Transport',isSubscription:false},
'addison lee':{name:'Addison Lee',category:'Transport',isSubscription:false},
'lime ':{name:'Lime',category:'Transport',isSubscription:false,_wordBound:true},
'voi ':{name:'Voi',category:'Transport',isSubscription:false,_wordBound:true},
'shell ':{name:'Shell',category:'Transport',isSubscription:false,_wordBound:true},
'bp ':{name:'BP',category:'Transport',isSubscription:false,_wordBound:true},
'esso':{name:'Esso',category:'Transport',isSubscription:false},
'texaco':{name:'Texaco',category:'Transport',isSubscription:false},
'avanti west':{name:'Avanti',category:'Transport',isSubscription:false},
'lner':{name:'LNER',category:'Transport',isSubscription:false},
'gwr ':{name:'GWR',category:'Transport',isSubscription:false,_wordBound:true},
'northern rail':{name:'Northern Rail',category:'Transport',isSubscription:false},

// FOOD DELIVERY (isSubscription: false) — delivery apps ONLY, NOT grocery shops
'deliveroo':{name:'Deliveroo',category:'Food Delivery',isSubscription:false},
'uber eats':{name:'Uber Eats',category:'Food Delivery',isSubscription:false},
'ubereats':{name:'Uber Eats',category:'Food Delivery',isSubscription:false},
'just eat':{name:'Just Eat',category:'Food Delivery',isSubscription:false},
'justeat':{name:'Just Eat',category:'Food Delivery',isSubscription:false},
'gousto':{name:'Gousto',category:'Food Delivery',isSubscription:true},
'hello fresh':{name:'HelloFresh',category:'Food Delivery',isSubscription:true},
'hellofresh':{name:'HelloFresh',category:'Food Delivery',isSubscription:true},

// GROCERIES — supermarkets and grocery shops, NOT food delivery
'tesco':{name:'Tesco',category:'Groceries',isSubscription:false},
'sainsbury':{name:'Sainsburys',category:'Groceries',isSubscription:false},
'asda':{name:'ASDA',category:'Groceries',isSubscription:false},
'morrisons':{name:'Morrisons',category:'Groceries',isSubscription:false},
'aldi':{name:'Aldi',category:'Groceries',isSubscription:false},
'lidl':{name:'Lidl',category:'Groceries',isSubscription:false},
'waitrose':{name:'Waitrose',category:'Groceries',isSubscription:false},
'ocado':{name:'Ocado',category:'Groceries',isSubscription:false},
'iceland':{name:'Iceland',category:'Groceries',isSubscription:false},
'marks spencer':{name:'M&S Food',category:'Groceries',isSubscription:false},
'm&s':{name:'M&S Food',category:'Groceries',isSubscription:false},
'co-op':{name:'Co-op',category:'Groceries',isSubscription:false},
'coop':{name:'Co-op',category:'Groceries',isSubscription:false},
'whole foods':{name:'Whole Foods',category:'Groceries',isSubscription:false},
'getir':{name:'Getir',category:'Groceries',isSubscription:false},
'gorillas':{name:'Gorillas',category:'Groceries',isSubscription:false},

// EATING OUT
'starbucks':{name:'Starbucks',category:'Eating Out',isSubscription:false},
'costa coffee':{name:'Costa',category:'Eating Out',isSubscription:false},
'costa ':{name:'Costa',category:'Eating Out',isSubscription:false},
'pret a manger':{name:'Pret',category:'Eating Out',isSubscription:false},
'pret ':{name:'Pret',category:'Eating Out',isSubscription:false},
'greggs':{name:'Greggs',category:'Eating Out',isSubscription:false},
'mcdonalds':{name:'McDonalds',category:'Eating Out',isSubscription:false},
'mcdonald':{name:'McDonalds',category:'Eating Out',isSubscription:false},
'nandos':{name:'Nandos',category:'Eating Out',isSubscription:false},
'nando':{name:'Nandos',category:'Eating Out',isSubscription:false},
'wagamama':{name:'Wagamama',category:'Eating Out',isSubscription:false},
'kfc':{name:'KFC',category:'Eating Out',isSubscription:false},
'burger king':{name:'Burger King',category:'Eating Out',isSubscription:false},
'five guys':{name:'Five Guys',category:'Eating Out',isSubscription:false},
'subway':{name:'Subway',category:'Eating Out',isSubscription:false},
'pizza express':{name:'Pizza Express',category:'Eating Out',isSubscription:false},
'pizza hut':{name:'Pizza Hut',category:'Eating Out',isSubscription:false},
'dominos':{name:'Dominos',category:'Eating Out',isSubscription:false},
'wetherspoon':{name:'Wetherspoons',category:'Eating Out',isSubscription:false},
'itsu':{name:'Itsu',category:'Eating Out',isSubscription:false},
'leon ':{name:'Leon',category:'Eating Out',isSubscription:false,_wordBound:true},
'tortilla':{name:'Tortilla',category:'Eating Out',isSubscription:false},
'gails':{name:'Gails',category:'Eating Out',isSubscription:false},
'gail s':{name:'Gails',category:'Eating Out',isSubscription:false},
'caffe nero':{name:'Caffe Nero',category:'Eating Out',isSubscription:false},
'eat.':{name:'EAT.',category:'Eating Out',isSubscription:false},
'eat ':{name:'EAT.',category:'Eating Out',isSubscription:false,_wordBound:true},
'franco manca':{name:'Franco Manca',category:'Eating Out',isSubscription:false},
'dishoom':{name:'Dishoom',category:'Eating Out',isSubscription:false},
'yo sushi':{name:'Yo! Sushi',category:'Eating Out',isSubscription:false},
'honest burger':{name:'Honest Burgers',category:'Eating Out',isSubscription:false},
'bills restaurant':{name:"Bill's",category:'Eating Out',isSubscription:false},
'cote ':{name:'Cote',category:'Eating Out',isSubscription:false},
'brewdog':{name:'Brewdog',category:'Eating Out',isSubscription:false},

// SHOPPING
'amazon':{name:'Amazon',category:'Shopping',isSubscription:false},
'amzn':{name:'Amazon',category:'Shopping',isSubscription:false},
'asos':{name:'ASOS',category:'Shopping',isSubscription:false},
'zara':{name:'Zara',category:'Shopping',isSubscription:false},
'ikea':{name:'IKEA',category:'Shopping',isSubscription:false},
'h&m':{name:'H&M',category:'Shopping',isSubscription:false},
'primark':{name:'Primark',category:'Shopping',isSubscription:false},
'uniqlo':{name:'Uniqlo',category:'Shopping',isSubscription:false},
'john lewis':{name:'John Lewis',category:'Shopping',isSubscription:false},
'next ':{name:'Next',category:'Shopping',isSubscription:false,_wordBound:true},
'next.co':{name:'Next',category:'Shopping',isSubscription:false},
'tk maxx':{name:'TK Maxx',category:'Shopping',isSubscription:false},
'tkmaxx':{name:'TK Maxx',category:'Shopping',isSubscription:false},
'ebay':{name:'eBay',category:'Shopping',isSubscription:false},
'shein':{name:'Shein',category:'Shopping',isSubscription:false},
'boohoo':{name:'Boohoo',category:'Shopping',isSubscription:false},
'currys':{name:'Currys',category:'Shopping',isSubscription:false},
'argos':{name:'Argos',category:'Shopping',isSubscription:false},
'apple store':{name:'Apple Store',category:'Shopping',isSubscription:false},
'nike':{name:'Nike',category:'Shopping',isSubscription:false},
'adidas':{name:'Adidas',category:'Shopping',isSubscription:false},
'gymshark':{name:'Gymshark',category:'Shopping',isSubscription:false},
'decathlon':{name:'Decathlon',category:'Shopping',isSubscription:false},
'waterstones':{name:'Waterstones',category:'Shopping',isSubscription:false},
'screwfix':{name:'Screwfix',category:'Shopping',isSubscription:false},
'b&q':{name:'B&Q',category:'Shopping',isSubscription:false},
'halfords':{name:'Halfords',category:'Shopping',isSubscription:false},
'sports direct':{name:'Sports Direct',category:'Shopping',isSubscription:false},
'river island':{name:'River Island',category:'Shopping',isSubscription:false},
'new look':{name:'New Look',category:'Shopping',isSubscription:false},
'matalan':{name:'Matalan',category:'Shopping',isSubscription:false},
'boots':{name:'Boots',category:'Health',isSubscription:false},
'superdrug':{name:'Superdrug',category:'Health',isSubscription:false},

// ENTERTAINMENT
'odeon':{name:'Odeon',category:'Entertainment',isSubscription:false},
'cineworld':{name:'Cineworld',category:'Entertainment',isSubscription:false},
'vue cinema':{name:'Vue',category:'Entertainment',isSubscription:false},
'curzon':{name:'Curzon',category:'Entertainment',isSubscription:false},
'steam':{name:'Steam',category:'Entertainment',isSubscription:false},
'playstation':{name:'PlayStation',category:'Entertainment',isSubscription:false},
'xbox':{name:'Xbox',category:'Entertainment',isSubscription:false},
'nintendo':{name:'Nintendo',category:'Entertainment',isSubscription:false},
'ticketmaster':{name:'Ticketmaster',category:'Entertainment',isSubscription:false},
'dice ':{name:'DICE',category:'Entertainment',isSubscription:false,_wordBound:true},
'dice.fm':{name:'DICE',category:'Entertainment',isSubscription:false},
'eventbrite':{name:'Eventbrite',category:'Entertainment',isSubscription:false},

// BILLS
'british gas':{name:'British Gas',category:'Bills',isSubscription:false},
'octopus energy':{name:'Octopus Energy',category:'Bills',isSubscription:false},
'octopus':{name:'Octopus Energy',category:'Bills',isSubscription:false},
'bulb':{name:'Bulb',category:'Bills',isSubscription:false},
'ovo energy':{name:'OVO Energy',category:'Bills',isSubscription:false},
'edf':{name:'EDF',category:'Bills',isSubscription:false},
'scottish power':{name:'Scottish Power',category:'Bills',isSubscription:false},
'council tax':{name:'Council Tax',category:'Bills',isSubscription:false},
'rent ':{name:'Rent',category:'Bills',isSubscription:false,_wordBound:true},
'rental':{name:'Rent',category:'Bills',isSubscription:false},
'mortgage':{name:'Mortgage',category:'Bills',isSubscription:false},
'thames water':{name:'Thames Water',category:'Bills',isSubscription:false},
'anglian water':{name:'Anglian Water',category:'Bills',isSubscription:false},
'united utilities':{name:'United Utilities',category:'Bills',isSubscription:false},
'severn trent':{name:'Severn Trent',category:'Bills',isSubscription:false},
'yorkshire water':{name:'Yorkshire Water',category:'Bills',isSubscription:false},
'water ':{name:'Water',category:'Bills',isSubscription:false,_wordBound:true},
'bt broadband':{name:'BT',category:'Bills',isSubscription:false},
'bt group':{name:'BT',category:'Bills',isSubscription:false},
'bt.com':{name:'BT',category:'Bills',isSubscription:false},
'sky tv':{name:'Sky',category:'Bills',isSubscription:false},
'sky digital':{name:'Sky',category:'Bills',isSubscription:false},
'sky broadband':{name:'Sky',category:'Bills',isSubscription:false},
'virgin media':{name:'Virgin Media',category:'Bills',isSubscription:false},
'plusnet':{name:'Plusnet',category:'Bills',isSubscription:false},
'hyperoptic':{name:'Hyperoptic',category:'Bills',isSubscription:false},
'ee ltd':{name:'EE',category:'Bills',isSubscription:false},
'ee mobile':{name:'EE',category:'Bills',isSubscription:false},
'vodafone':{name:'Vodafone',category:'Bills',isSubscription:false},
'o2 uk':{name:'O2',category:'Bills',isSubscription:false},
'three mobile':{name:'Three',category:'Bills',isSubscription:false},
'three.co':{name:'Three',category:'Bills',isSubscription:false},
'giffgaff':{name:'Giffgaff',category:'Bills',isSubscription:false},
'tv licence':{name:'TV Licence',category:'Bills',isSubscription:false},
'insurance':{name:'Insurance',category:'Bills',isSubscription:false},

// HEALTH
'bupa':{name:'Bupa',category:'Health',isSubscription:false},
'dentist':{name:'Dentist',category:'Health',isSubscription:false},
'pharmacy':{name:'Pharmacy',category:'Health',isSubscription:false},
'optician':{name:'Optician',category:'Health',isSubscription:false},
'specsavers':{name:'Specsavers',category:'Health',isSubscription:false},
'vision express':{name:'Vision Express',category:'Health',isSubscription:false},

// TRAVEL
'ryanair':{name:'Ryanair',category:'Travel',isSubscription:false},
'easyjet':{name:'easyJet',category:'Travel',isSubscription:false},
'british airways':{name:'British Airways',category:'Travel',isSubscription:false},
'jet2':{name:'Jet2',category:'Travel',isSubscription:false},
'wizz air':{name:'Wizz Air',category:'Travel',isSubscription:false},
'wizzair':{name:'Wizz Air',category:'Travel',isSubscription:false},
'tui ':{name:'TUI',category:'Travel',isSubscription:false,_wordBound:true},
'booking.com':{name:'Booking.com',category:'Travel',isSubscription:false},
'airbnb':{name:'Airbnb',category:'Travel',isSubscription:false},
'hotels.com':{name:'Hotels.com',category:'Travel',isSubscription:false},
'expedia':{name:'Expedia',category:'Travel',isSubscription:false},
'skyscanner':{name:'Skyscanner',category:'Travel',isSubscription:false},
'eurostar':{name:'Eurostar',category:'Travel',isSubscription:false},
'national express':{name:'National Express',category:'Travel',isSubscription:false},

// CHARITY
'justgiving':{name:'JustGiving',category:'Charity',isSubscription:false},
'gofundme':{name:'GoFundMe',category:'Charity',isSubscription:false},
'charity':{name:'Charity',category:'Charity',isSubscription:false},
'donation':{name:'Donation',category:'Charity',isSubscription:false},
'cancer research':{name:'Cancer Research',category:'Charity',isSubscription:false},
'british heart':{name:'British Heart Foundation',category:'Charity',isSubscription:false},
'red cross':{name:'Red Cross',category:'Charity',isSubscription:false},
'oxfam':{name:'Oxfam',category:'Charity',isSubscription:false},
'macmillan':{name:'Macmillan',category:'Charity',isSubscription:false},

// EDUCATION
'udemy':{name:'Udemy',category:'Education',isSubscription:false},
'coursera':{name:'Coursera',category:'Education',isSubscription:false},
'linkedin learning':{name:'LinkedIn Learning',category:'Education',isSubscription:false},
'student loan':{name:'Student Loan',category:'Education',isSubscription:false},
'student loans':{name:'Student Loan',category:'Education',isSubscription:false},
'university':{name:'University',category:'Education',isSubscription:false},
'tuition':{name:'Tuition',category:'Education',isSubscription:false},
'nursery':{name:'Nursery',category:'Education',isSubscription:false},
'school fees':{name:'School Fees',category:'Education',isSubscription:false},

// SAVINGS & INVESTMENTS (not counted as spending)
'vanguard':{name:'Vanguard',category:'Savings',isSubscription:false},
'nutmeg':{name:'Nutmeg',category:'Savings',isSubscription:false},
'freetrade':{name:'Freetrade',category:'Savings',isSubscription:false},
'trading 212':{name:'Trading 212',category:'Savings',isSubscription:false},
'hargreaves':{name:'Hargreaves Lansdown',category:'Savings',isSubscription:false},
'aj bell':{name:'AJ Bell',category:'Savings',isSubscription:false},
'moneybox':{name:'Moneybox',category:'Savings',isSubscription:false},
'plum ':{name:'Plum',category:'Savings',isSubscription:false,_wordBound:true},
'chip ':{name:'Chip',category:'Savings',isSubscription:false,_wordBound:true},

// INCOME — only genuine income sources, NOT refunds
'salary':{name:'Salary',category:'Income',isSubscription:false},
'wages':{name:'Wages',category:'Income',isSubscription:false},
'payroll':{name:'Payroll',category:'Income',isSubscription:false},
'interest':{name:'Interest',category:'Income',isSubscription:false},
'dividend':{name:'Dividend',category:'Income',isSubscription:false},
'hmrc':{name:'HMRC',category:'Income',isSubscription:false},
'tax refund':{name:'Tax Refund',category:'Income',isSubscription:false},
'bacs':{name:'BACS Payment',category:'Income',isSubscription:false},
'chaps':{name:'CHAPS Payment',category:'Income',isSubscription:false},
'dwp':{name:'DWP',category:'Income',isSubscription:false},
'universal credit':{name:'Universal Credit',category:'Income',isSubscription:false},
'child benefit':{name:'Child Benefit',category:'Income',isSubscription:false},
'tax credits':{name:'Tax Credits',category:'Income',isSubscription:false},
'pension':{name:'Pension',category:'Income',isSubscription:false},
'state pension':{name:'State Pension',category:'Income',isSubscription:false},
'jobseeker':{name:'Jobseekers Allowance',category:'Income',isSubscription:false},
'sage payroll':{name:'Sage Payroll',category:'Income',isSubscription:false},
'xero payroll':{name:'Xero Payroll',category:'Income',isSubscription:false},
'brightpay':{name:'BrightPay',category:'Income',isSubscription:false},
'moorepay':{name:'Moorepay',category:'Income',isSubscription:false},
'adp payroll':{name:'ADP Payroll',category:'Income',isSubscription:false},
'ceridian':{name:'Ceridian',category:'Income',isSubscription:false},
'iris payroll':{name:'IRIS Payroll',category:'Income',isSubscription:false},
'autopay':{name:'Autopay',category:'Income',isSubscription:false},
'payroll solutions':{name:'Payroll Solutions',category:'Income',isSubscription:false},
'payroll services':{name:'Payroll Services',category:'Income',isSubscription:false},

// REFUNDS — credits but not income (excluded from income calculations)
'refund':{name:'Refund',category:'Refund',isSubscription:false},
'reversal':{name:'Reversal',category:'Refund',isSubscription:false},
'cashback':{name:'Cashback',category:'Refund',isSubscription:false}
};

export default MERCHANT_DB;
